### ISSUE TITLE
Ember generate command trying to overwrite template

### ISSUE THREAD

**Issue by Globegitter** [sane/sane-auth#10]
Not necessarily a bug, but should see how we handle this: https://github.com/Globegitter/sane-auth/blob/master/generate/templates/client/app/routes/user.js is there, but https://github.com/Globegitter/sane-auth/blob/master/generate/client.js#L67 then asks to overwrite this.

Should we do anything about it? But it does mess up the acceptance tests now :P Would be great to have a `--force` flag for `ember generate`

Other options would be to just generate the `model` and `template` instead of a resource, which would skip the route.

**Comment by mgenev** [comment]
I think the 2nd solution is alright - generate the model and template instead of a resource, which would skip the route.
