### ISSUE TITLE
enable chosen DB in server/config/env/development.js

### ISSUE THREAD

**Issue by Jan-Jan** [sane/sane-auth#14]
After installing sane-auth I still needed to edit server/config/env/development.js to get it working, by adding

```
  models: {
    connection: 'mongo'
  }
```

Please either enable by default based on the chosen DB, or add instruction as part of installation.

PS. Love the work you are doing. Please keep it up.

**Comment by Globegitter** [comment]
@Jan-Jan that is odd - how did you set up your sane project (e.g. `sane new project -d mongo`)? That should be independent of this addon and is being set in `server/config/models.js`.

Glad this is useful to you :)
